# Generated by Django 5.0.13 on 2026-06-17 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, db_column='EMPRESA', help_text='Nombre de la Empresa Asociada.', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Fact Empresa',
                'verbose_name_plural': 'Fact Empresas',
                'db_table': 'FACT_EMPRESA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fact_UpdateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fact', models.IntegerField(blank=True, db_column='ID_FACT', help_text='ID único de la Boleta o Factura.')),
                ('nro_fact', models.CharField(blank=True, db_column='NUMERO_FACTURA', help_text='Nro de documento de la Boleta o Factura.', max_length=20, null=True)),
                ('estado_old', models.TextField(blank=True, db_column='ESTADO_OLD', help_text='Estado del registro antes de hacer las modificaciones.', null=True)),
                ('estado_new', models.TextField(blank=True, db_column='ESTADO_NEW', help_text='Estado del registro después de hacer las modificaciones.', null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, db_column='FECHA_HORA', help_text='Fecha y Hora en la que el usuario que realizo modificaciones en el registro.', null=True)),
                ('usuario', models.CharField(blank=True, db_column='USUARIO', help_text='Nombre del usuario que realizo modificaciones en el registro.', max_length=60, null=True)),
                ('empr_id', models.ForeignKey(blank=True, db_column='EMPRESA_ID', help_text='Número de ID de la empresa asociada responsable de la Boleta o Factura.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empr_audit', to='facturacion.fact_empresa')),
            ],
            options={
                'verbose_name': 'Fact Audit',
                'verbose_name_plural': 'Fact Audits',
                'db_table': 'FACT_UPDATE_AUDIT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_fact', models.CharField(blank=True, db_column='NUMERO_FACTURA', help_text='Nro de documento de la Boleta o Factura.', max_length=20, null=True)),
                ('cod_form', models.CharField(blank=True, db_column='CODIGO_FORMULARIO', help_text='Código del Formulario de la Boleta o Factura.', max_length=6, null=True)),
                ('nro_form', models.IntegerField(blank=True, db_column='NUMERO_FORMULARIO', help_text='Número del Formulario de la Boleta o Factura.', null=True)),
                ('comprobante', models.CharField(blank=True, db_column='COMPROBANTE', help_text='Número de Comprobante de la Boleta o Factura.', max_length=20, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, db_column='FECHA_EMISION', help_text='Fecha y Hora en que se generó la Boleta o Factura.', null=True)),
                ('monto', models.DecimalField(blank=True, db_column='MONTO', decimal_places=2, help_text='Monto Total de la Boleta o Factura.', max_digits=18, null=True)),
                ('moneda', models.CharField(blank=True, db_column='MONEDA', help_text='Moneda del Monto Total de la Boleta o Factura.', max_length=60, null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='NOMBRE_CLIENTE', help_text='Nombre del cliente.', max_length=150, null=True)),
                ('cond_pago', models.CharField(blank=True, db_column='CONDICION_PAGO', help_text='Condición de Pago.', max_length=60, null=True)),
                ('vendedor', models.CharField(blank=True, db_column='VENDEDOR', help_text='Nombre del Vendedor.', max_length=60, null=True)),
                ('cancelado', models.CharField(blank=True, db_column='CANCELADO', help_text='Estado de cancelación de la Boleta o Factura. S=Cancelado - N=Falta Cancelar', max_length=1, null=True)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', help_text='Estado de la Boleta o Factura. ACT=Activo - ANU=Anulado', max_length=3, null=True)),
                ('cobrado', models.DecimalField(blank=True, db_column='COBRADO', decimal_places=2, help_text='Monto Cobrado de la Boleta o Factura.', max_digits=18, null=True)),
                ('saldo', models.DecimalField(blank=True, db_column='SALDO', decimal_places=2, help_text='Monto que falta cobrar de la Boleta o Factura.', max_digits=18, null=True)),
                ('nc_canje_fact', models.CharField(blank=True, db_column='NC_CANJE_FACTURA', help_text='Factura que tiene Nota de Crédito de Canje.', max_length=120, null=True)),
                ('nc_fact_canje', models.CharField(blank=True, db_column='NC_FACTURA_CANJE', help_text='Nota de Crédito de Canje.', max_length=20, null=True)),
                ('nc_anulacion', models.CharField(blank=True, db_column='NC_ANULACION', help_text='Nota de Crédito de Anulación de Factura.', max_length=35, null=True)),
                ('titulo_grat', models.CharField(blank=True, db_column='TITULO_GRATUITO', help_text='Título gratuito.', max_length=1, null=True)),
                ('dir_entr', models.CharField(blank=True, db_column='DIRECCION_ENTREGA', help_text='Dirección de Entrega de la Boleta o Factura.', max_length=255, null=True)),
                ('dir_fact', models.CharField(blank=True, db_column='DIRECCION_FACTURACION', help_text='Dirección de Facturación.', max_length=60, null=True)),
                ('id_app', models.IntegerField(blank=True, db_column='ID_APP', help_text='ID del Formulario de Solicitud de Pedidos relacionada a la Boleta o Factura.', null=True)),
                ('oc_cliente', models.CharField(blank=True, db_column='OC_CLIENTE', help_text='Nro de Orden de Compra de la Boleta o Factura.', max_length=20, null=True)),
                ('tipo_cliente', models.CharField(blank=True, db_column='TIPO_CLIENTE', help_text='Tipo de Cliente. PÚBLICO o PRIVADO', max_length=60, null=True)),
                ('tipo_venta', models.CharField(blank=True, db_column='TIPO_VENTA', help_text='Tipo de Venta. Permite excluir CANJES', max_length=6, null=True)),
                ('usuario_registro', models.CharField(blank=True, db_column='USUARIO_REGISTRO', help_text='Usuario que generó la Boleta o Factura.', max_length=15, null=True)),
                ('zona', models.CharField(blank=True, db_column='ZONA', help_text='Nombre de la Zona de Entrega.', max_length=60, null=True)),
                ('afecto_detr', models.CharField(blank=True, db_column='AFECTO_DETRACCION', help_text='Verifica si Corresponde Detracción. S=Sí - N=No', max_length=1, null=True)),
                ('afecto_ret', models.CharField(blank=True, db_column='AFECTO_RETENCION', help_text='verifica si Corresponde Retención. S=Sí - N=No', max_length=1, null=True)),
                ('monto_soles', models.DecimalField(blank=True, db_column='MONTO_SOLES', decimal_places=2, help_text='Monto Total en Soles de la Boleta o Factura.', max_digits=18, null=True)),
                ('usuario', models.CharField(blank=True, db_column='USUARIO', help_text='Usuario que modificó la Boleta o Factura.', max_length=120, null=True)),
                ('empr_id', models.ForeignKey(blank=True, db_column='EMPRESA_ID', help_text='Número de ID de la empresa asociada responsable de la Boleta o Factura.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.fact_empresa')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'FACT_DETALLE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fact_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.CharField(blank=True, db_column='COMPROBANTE', help_text='Número de Comprobante de la Boleta o Factura.', max_length=20, null=True)),
                ('nro_item', models.IntegerField(blank=True, db_column='NUMERO_ITEM', help_text='Nro de Item del Producto de la Boleta o Factura.', null=True)),
                ('tipo_producto', models.CharField(blank=True, db_column='TIPO_PRODUCTO', help_text='Tipo de Producto.', max_length=6, null=True)),
                ('prod', models.CharField(blank=True, db_column='PRODUCTO', db_index=True, help_text='Nro de Serie del Producto.', max_length=30, null=True)),
                ('cantidad', models.DecimalField(blank=True, db_column='CANTIDAD', decimal_places=2, help_text='Cantidad de Productos por Lote.', max_digits=18, null=True)),
                ('precio_unit', models.DecimalField(blank=True, db_column='PRECIO_UNITARIO', decimal_places=2, help_text='Precio unitario en Soles del Producto de la Boleta o Factura.', max_digits=18, null=True)),
                ('precio_soles', models.DecimalField(blank=True, db_column='PRECIO_SOLES', decimal_places=2, help_text='Precio Total en Soles del Producto de la Boleta o Factura. CANTIDAD x PRECIO_UNITARIO', max_digits=18, null=True)),
                ('comision_pagada', models.BooleanField(blank=True, db_column='COMISION_PAGADA', default=False, help_text='Indica si la Comsión de este producto fue pagada al respectivo representante.', null=True)),
                ('comision_pagada_sup', models.BooleanField(blank=True, db_column='COMISION_PAGADA_SUPERVISOR', default=False, help_text='Indica si la Comsión de este producto fue pagada al respectivo Supervisor.', null=True)),
                ('usuario', models.CharField(blank=True, db_column='USUARIO', help_text='Usuario que modificó los items de la Boleta o Factura.', max_length=120, null=True)),
                ('fact_id', models.ForeignKey(blank=True, db_column='FACT_ID', help_text='ID único de la Boleta o Factura.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fd', to='facturacion.facturas')),
            ],
            options={
                'verbose_name': 'Factura Detalle',
                'verbose_name_plural': 'Facturas Detalle',
                'db_table': 'FACTURAS',
                'managed': True,
            },
        ),
    ]
